### ISSUE TITLE
NWC-only mode?

### ISSUE THREAD

**Issue by futurepaul** [getAlby/bitcoin-connect#89]
I'd like to use this button for getting an NWC string but don't want my app to have to know all about webLN as well. is there a way to put this into "nwc only" mode so it gets NWC strings from alby and mutiny but doesn't do any other protocols?

**Comment by rolznz** [comment]
Hi @futurepaul, thanks for reporting.

Similar to https://github.com/getAlby/bitcoin-connect/issues/11 - I will close it for now

**Comment by rolznz** [comment]
@futurepaul this should be possible now with passing the `filters="nwc"` attribute to the button or modal.

**Comment by rolznz** [comment]
@futurepaul we currently don't have a public interface for getting the NWC string because Bitcoin Connect only exposes the WebLN interface. You can get it from the webln object that is added to the window once the connection is connected, but I'll keep this open until we find a better way to expose that (and how NWC in general fits in with Bitcoin Connect which was originally focused on WebLN)

**Comment by rolznz** [comment]
Currently the NWC string is available at `window.webln.nostrWalletConnectUrl` after connecting but this is not publicly exposed. This is a problem is shown in the [ZapPlanner PR to add Bitcoin Connect](https://github.com/getAlby/ZapPlanner/pull/63) - we need a nice way to expose additional capabilities outside of webln that is not biased to just NWC but also supports other connector capabilities CC @bumi @reneaaron

**Comment by rolznz** [comment]
This will be solved in the next major version of Bitcoin Connect (https://github.com/getAlby/bitcoin-connect/pull/140):

```
import { WebLNProviders, requestProvider } from "@getalby/bitcoin-connect";

const provider = await requestProvider();

if (provider instanceof WebLNProviders.NostrWebLNProvider) {
  // do something with provider.nostrWalletConnectUrl;
}
```
